<div class="note-container">
    <h3>Onshore:</h3>
    <div class="onshore-container">
        <ul>
            <li>Person 1</li>
            <li>Person 2</li>
            <li>Person 3</li>
        </ul>
    </div>
    <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/right_arrow_large.gif') ?>" class="navarrow" />
    <label class="pagelabel">Page 1 of 1</label>
    <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/left_arrow_large.gif') ?>" class="navarrow" />
    <h3>Offshore:</h3>
    <div class="offshore-container">
        <ul>
            <li>Person 4</li>
            <li>Person 5</li>
            <li>Person 6</li>
        </ul>
    </div>
    <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/right_arrow_large.gif') ?>" class="navarrow" />
    <label class="pagelabel">Page 1 of 1</label>
    <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/left_arrow_large.gif') ?>" class="navarrow" />
</div>
<div class="body-container">
    <?php echo $this->form ?>
    <form action="./addProject.php" method="post">
        <div class="NewBudget">
            <h1>New Project -> Budget</h1>
            <h2>Budget Information</h2>
            <label>Role:</label>
            <select>
                <option value="Project Manager">Project Manager</option>
                <option value="Java Developer">Java Developer</option>
                <option value="Java Designer">Java Designer</option>
                <option value="UI Developer">UI Developer</option>
                <option value="Tester">Tester</option>
            </select><br>
            <div class="lookup">
                <label>Resource:</label>
                <a href="javascript:void(0)" onclick="lookup(600,400, 'resource', 'People');">
                    <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/LookupIcon.gif')?>" />
                </a>
                <input id="resource" name="resource" type="text" required readonly>
                <input type="hidden" id="hidden_resource" name="hidden_resource" ><br>
            </div>
            <label>Location:</label>
            <select>
                <?php
                    //populate from query
                ?>
                <option value="North America">North America</option>
                <option value="Group">Group</option>
                <option value="Rightshore">Rightshore</option>
                <option value="External">External</option>
            </select><br>
            <label>Staffing Level:</label>
            <select>
                <?php
                    //populate from query
                ?>
                <option value="Consultant">Consultant</option>
                <option value="Senior Consultant">Senior Consultant</option>
                <option value="Manager">Manager</option>
                <option value="Senior Manager">Senior Manager</option>
                <option value="Principal">Principal</option>
                <option value="Vice President ">Vice President </option>
            </select><br>
            <label>ChargeOut Level:</label>
            <input type="number" min="1" max="7" value="4">
            <br>
            <label>Expense Rate: $</label>
            <input type="text" name="expense_rate"><br>
            <label>Traveler:<label>
            <input type="checkbox"><br>
            <button type="submit">Back</button>
            <button type="submit">Add More</button>
            <button type="submit">Save Budget</button>
        </div>
    </form>
</div>