<div>
	<h1>Statement of Work:</h1>
	<h2>
		<a
			href="<?php echo $this->baseUrl('/contracts/view/id/'.$this->project->sow->_id) ?>">
			<?php echo $this->project->sow->contract_number ?>
		</a>
	</h2>
	<h1>Change Orders:</h1>
	<?php foreach($this->project->change_orders as $contract): ?>
	<h2>
		<a
			href="<?php echo $this->baseUrl('/contracts/view/id/'.$contract->_id) ?>">
			<?php echo $contract->contract_number ?>
		</a>
	</h2>
	<?php endforeach; ?>
</div>