<div>
<h1>Responsible:</h1>
<h2>
<a href="<?php echo $this->baseUrl('/resources/view/id/'.$this->project->responsible->_id) ?>">
			<?php echo $this->project->responsible->name->first . ' ' . $this->project->responsible->name->last?>
		</a>
	</h2>
	<h1>Accountable:</h1>
	<h2><?php echo $this->project->accountable->name->first . ' ' . $this->project->accountable->name->last?></h2>
	<h1>ETC Keeper:</h1>
	<h2><?php echo $this->project->etc_keeper->name->first . ' ' . $this->project->etc_keeper->name->last?></h2>
	<h1>Expense Approver:</h1>
	<h2><?php echo $this->project->expense_approver->name->first . ' ' . $this->project->expense_approver->name->last?></h2>
</div>
