<div class="body-container">
	<h1><?php echo $this->project->name ?></h1>
	<b>Are you sure you want to delete this project? This action is irreversible.</b>
	<form method="post" action="/projects/delete/id/<?php  echo $this->project->id ?>">
		<input type="hidden" value="true"/>
		<input type="submit" value="Delete" class="pill-btn black-btn" />
		<a href="/projects/view/id/<?php echo $this->project->id ?>" class="pill-btn black-btn">Back</a>
	</form>
</div>