<div class="body-container">
    <p><?php echo $this->projects->count() ?> Active</p>
    <p>List of projects:</p>
    <?php var_dump($this->projects); ?>
    <ul id="itemList">
        <?php echo $this->partialLoop('projects/partials/projectList.phtml', $this->projects) ?>
    </ul>
    <a href="/projects/new/" class="pill-btn black-btn">New Project</a>
    <form>
        <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/right_arrow_large.gif') ?>" class="navarrow" />
        <label class="pagelabel">Page 1 of 1</label>
        <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/left_arrow_large.gif') ?>" class="navarrow" />
    </form>
</div>