<div class="side-container">
    <p>Import from Opportunity</p>
    <p>SPADE ID:</p>
    <input type="text"><br>
    <a href="/projects/import/" class="pill-btn black-btn">Import</a>
</div>
<div class="note-container">
    <p>Importing the Project by Opportunity will add the following data</p>
    <ul>
        <li>Name of the Project</li>
        <li>Project Code</li>
        <li>Duration</li>
    </ul>
</div>
<div class="body-container">
	<h1>New Project</h1>
    <?php echo $this->form ?>
</div>