<div class="body-container">
	<h1>
		<?php echo $this->project->name?>
	</h1>
	<div id="tabs">
		<ul>
			<li><a href="#tabs-general">General Information</a>
			</li>
			<li><a href="#tabs-contract">Change Orders</a>
			</li>
			<li><a href="#tabs-budget">Roles</a>
			</li>
			<li><a href="#tabs-config"><img
					src="<?php echo $this->baseUrl('/media/site/img/content/icons/gear.jpeg') ?>"
					height="12" width="12">

			</li>
		</ul>
		<div id="tabs-general">
			<h3>General Information</h3>
			<label>Code: <?php echo $this->project->code ?>
			</label><br> Accountable:
			<?php echo $this->accountable->last_name . ', ' . $this->accountable->first_name ?>
			<br> Responsible:
			<?php echo $this->responsible->last_name . ', ' . $this->responsible->first_name ?>
			<br> ETC Keeper:
			<?php echo $this->etc_keeper->last_name . ', ' . $this->etc_keeper->first_name ?>
			<br> Expense Approver:
			<?php echo $this->expense_approver->last_name . ', ' . $this->expense_approver->first_name ?>
			<br> Phase:
			<?php echo $this->project->phase ?>
			<br> Status:
			<?php echo $this->project->status ?>
			<br> Start Date:
			<?php echo $this->start_date ?>
			<br> End Date:
			<?php echo $this->end_date?>
			<br> <br> <a
				href="<?php echo $this->url(
		            array('controller' => 'roles', 'action' => 'new', 'cid' => $this->id),
					null,
					TRUE
	        	);?>"
				class="pill-btn black-btn">New Role</a>
		</div>
		<div id="tabs-contract">
			<ul id="itemList">
				<?php echo $this->partialLoop('contracts/partials/contractList.phtml', $this->contracts) ?>
			</ul>
			<a
				href="<?php echo $this->url(
		            array('controller' => 'contracts', 'action' => 'new', 'pid' => $this->id),
					null,
					TRUE
		        );?>"
				class="pill-btn black-btn">Add Contract</a>
		</div>
		<div id="tabs-budget">
			<a
				href="<?php echo $this->url(
		            array('controller' => 'roles', 'action' => 'new', 'cid' => $this->id),
					null,
					TRUE
		        );?>"
				class="pill-btn black-btn">Add Role</a>
		</div>
		<div id="tabs-config">
			<a
				href="<?php echo $this->url(
		            array('controller' => 'projects', 'action' => 'delete', 'pid' => $this->id),
					null,
					TRUE
				);?>"
				class="pill-btn black-btn">Delete Project</a> <a
				href="<?php echo $this->url(
	            	array('controller' => 'projects', 'action' => 'edit', 'id' => $this->id),
					null,
					TRUE
				);?>"
				class="pill-btn black-btn">Edit</a>
		</div>
	</div>
</div>
