<div class="body-container">
    <div class="text-container">
		<p>
			This is an application that is in development to help CapGemini with managing projects.
		</p>
		<h2>Functionality:</h2>
		<ul>
			<li>Resource management</li>
			<li>Project timeline planning</li>
		</ul>

		<h2>Log In</h2>
		<form action="/dashboard/" method="post">
			<input name="username" type="text" placeholder="username">
			<br>
			<input name="password" type="password" placeholder="password">
			<br>
			<button type="submit">Log In</button>
		</form>
		<p>
			For more information about CapGemini, please visit
			<a href="http://www.capgemini.com/">www.capgemini.com</a>.
		</p>
	</div>
</div>