<h1>Office Base:</h1>
<h2><?php echo $this->resource->office_base->city .
', ' .
$this->resource->office_base->state .
', ' .
$this->resource->office_base->country ?></h2>
<h1>Capgemini Email:</h1>
<h2><?php echo $this->resource->email->capgemini ?></h2>
<h1>Personal Address:</h1>
<h2><?php echo $this->resource->address->line1 . '<br>' .
$this->resource->address->line2 . '<br>' .
$this->resource->address->city . '<br>' .
$this->resource->address->state . '<br>' .
$this->resource->address->country ?></h2>
<h1>1+7:</h1>
<h2><?php echo $this->resource->username;?></h2>
<h1>Resource Type:</h1>
<h2><?php echo $this->resource->resource_type->value; ?></h2>
