<div class="body-container">
    <p><?php echo $this->results->count() ?> Active</p>
    <p>List of resources:</p>
    <ul id="itemList">
        <?php echo $this->partialLoop('resources/partials/resourceList.phtml', $this->results) ?>
    </ul>
    <a href="/resources/new/" class="pill-btn black-btn">New Resource</a>
    <form method="post">
        <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/right_arrow_large.gif') ?>" class="navarrow" />
        <label class="pagelabel">Page 1 of 1</label>
        <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/left_arrow_large.gif') ?>" class="navarrow" />
    </form>
</div>