<div class="body-container">
    <p><?php echo $this->resources->count() ?> Active</p>
    <p>List of resources:</p>
    <ul id="itemList">
        <?php foreach($this->resources as $resource): ?>
        <li>
		    <a href="<?php echo $this->url(
		            array(
		                    'controller' => 'resources',
		                    'action' => 'view',
		                    'id' => $resource->_id
		            )
		    ); ?>">
		        <?php echo $resource->name->last . ", " . $resource->name->first ?>
		    </a>
		</li>
        <?php endforeach;?>
    </ul>
    <a href="/resources/new/" class="pill-btn black-btn">New Resource</a>
    <form method="post">
        <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/right_arrow_large.gif') ?>" class="navarrow" />
        <label class="pagelabel">Page 1 of 1</label>
        <img src="<?php echo $this->baseUrl('/media/site/img/content/icons/left_arrow_large.gif') ?>" class="navarrow" />
    </form>
</div>