<div class="hero-panel" id="profile-hero-panel">
	<div class="left">
		<img alt=""
			src="https://s3.amazonaws.com/Capgemini/Avatars/msholty.jpg"
		<!--<form method="POST" enctype="multipart/form-data">
					Please upload a profile picture: <input type="file" name="pic" /> <input
						type="submit" />
				</form>-->
	</div>

	<div class="right">
		<h1 class="main-content-section-title">
			<?php echo $this->resource->name->first . ' ' . $this->resource->name->last ?>
		</h1>
		<h2>
			<?php echo $this->resource->title->value ?>
		</h2>
		<h3>
			<?php echo $this->phoneNumber($this->resource->phone_number) ?>
		</h3>
		<h3>
			Anjan Aluru
		</h3>
	</div>
</div>

<ul id="profile-stats-panel">
	<li id="stat-level">
		<div class="li-container">
			<div class="stat-value">AppsOne East</div>
			<div class="stat-label">Business Unit</div>
		</div>
	</li>

	<li id="stat-level">
		<div class="li-container">
			<div class="stat-value">EA&IS</div>
			<div class="stat-label">Service Line</div>
		</div>
	</li>

	<li id="stat-level">
		<div class="li-container">
			<div class="stat-value">2202787</div>
			<div class="stat-label">UPN</div>
		</div>
	</li>

	<li id="stat-level">
		<div class="li-container">
			<div class="stat-value">Sept 11</div>
			<div class="stat-label">ETC Month-Year</div>
		</div>
	</li>


	<li id="stat-level">
		<div class="li-container">
			<div class="stat-value">Onshore</div>
			<div class="stat-label">Location</div>
		</div>
	</li>


</ul>
<div class="sidebar-column">
	<div>
		<?php echo $this->profileNavigation() ?>
	</div>
</div>
<div id="profile-content">test
</div>
