<div class="header">
	<div id="left">
	    <a href="http://www.capgemini.com">
	        <img src="<?php echo $this->baseUrl('/media/site/img/content/title-bar/CapGemini.png') ?>" alt="CapGemini" />
	    </a>
	</div>
	<div id="right">
	    <a href="http://disneyworld.disney.go.com/">
	        <img src="<?php echo $this->baseUrl('/media/site/img/content/title-bar/WaltDisney.png') ?>" alt="Walt Disney" />
	    </a>
	</div>
	<div id="middle">
		<a href="<?php echo $this->baseUrl(); ?>"><h1>Account as a Platform</h1></a>
	</div>
	<div id="bottom"></div>
</div>