<nav id="globalheader">
	<ul id="list-nav">
	    <li><a id="nav_opportunities" class="first" href="./opportunities/"><span>Opportunities</span></a></li>
	    <li><a id="nav_projects" href="./projects/"><span>Projects</span></a></li>
	    <li><a id="nav_financials" href="./financials/">Financials</a></li>
	    <li><a id="nav_resources" href="./resources/">Resources</a></li>
	    <li><a id="nav_qa" href="./qa/">Q/A</a></li>
	    <li><a id="nav_reports" class="last" href="./reports/">Reports</a></li>
	</ul>
</nav>