<?php
/**
 * CapGemini Web Application
 *
 * (c) CapGemini.  All rights reserved.
 *
 *
 * @package Default_Layout
 * @subpackage Script
 * @copyright (c) Capgemini.  All rights reserved.
 */
?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></meta>
    <title>Capfire: Capgemini Finances and Resource Management Platform</title>
    <?php
    $this->headLink()
		->prependStylesheet(
				$this->baseUrl(
						'/media/shared/jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css'
				),
				'screen'
		)
		->prependStylesheet(
				$this->baseUrl(
						'/media/site/css/maxwidth961.css'
				),
				'screen'
		)
		->prependStylesheet(
				$this->baseUrl(
						'/media/site/css/style.css'
				),
				'screen'
		)
        ->headLink(
                array('rel' => 'icon',
                    'href' => $this->baseUrl('/media/site/img/content/favicon.ico')),
                    'PREPEND');
    echo $this->headLink();
    ?>

    <script type="text/javascript" src="<?php echo $this->baseUrl('/media/shared/jquery-ui/js/jquery-1.8.0.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/media/shared/jquery-ui/js/jquery-ui-1.8.23.custom.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/media/site/js/jscript.js'); ?>"></script>
</head>
