<?php if ($this->pageCount): ?>
<nav class="dot-nav">
	<ul>
		<?php $x=0;?>
		<?php while($x++ < $this->pageCount): ?>
		<li><a class="hero-gallery active" href="#page<?php echo $x ?>"
			onclick="">Profile Card Deck</a>
		</li>
		<?php endwhile; ?>
	</ul>
</nav>
<nav class="paddle-nav">
	<ul>
		<?php if (isset($this->previous)): ?>
		<li><a class="arrow prev hero-gallery" href="#previous" onclick=""><b>Previous</b>
		</a></li>
		<?php endif; ?>
		<?php if (isset($this->next)): ?>
		<li><a class="arrow next hero-gallery" href="#next" onclick=""><b>Next</b>
		</a></li>
		<?php endif; ?>
	</ul>
</nav>
<?php endif; ?>
